[package]
name = "scalpel"
version = "0.1.0"
authors = ["Bernhard Schuster <bernhard@nello.io>"]

[features]
default = ["v1", "v2"]
v1 = ["rust-crypto", "base64"]
v2 = ["nom", "bitflags", "bytes", "tokio-io", "linked-hash-map", "enum-primitive-derive", "num", "num-traits", "eui48"]



[dependencies]
docopt = "0.8"
serde = "1.0"
serde_derive = "1.0"
log = "0.4"
env_logger = "0.5"
#sodiumoxide = "^0.0.16"
#ring = "^0.12"
#webpki = "^0.17"

bytes = { version = "*", optional = true }
ring = "0.12.1"

rust-crypto = { version = "*", optional = true }
time = "^0.1"
rand = "^0.4"
rand_derive = "^0.3"
base64 = { version = "~0.6.0", optional = true }

failure = "*"
failure_derive = "*"

lazy_static = "*"
regex = "*"
chrono = { version = "^0.4", features = ["serde"] }

webpki = "^0.17"
untrusted = "0.5.1"

linked-hash-map = { version = "0.5", features = ["serde_impl"], optional = true }
nom = { version = "^3.2", optional = true }
bitflags = { version =  "^1.0", optional = true }
tokio-io = { version = "*", optional = true }

num =  { version = "^0.1", optional = true }
enum-primitive-derive = { version = "^0.1", optional = true }
num-traits = { version = "^0.1", optional = true }

eui48 = {version = "^0.3.2", optional = true}

